name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissions zaroori hain
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          # GIF output
          outputs: dist/github-snake.gif

      # Nayi branch (output) banane ke liye:
      - uses: EndBug/add-and-commit@v9
        with:
          branch: output
          default_author: github_actions
          message: 'ğŸ Snake GIF generated'
          add: 'dist/github-snake.gif'
          # Force commit zaroori hai agar branch pehle se ho:
          force: true
