name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ye line permissions ko confirm karta hai
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          # Yahaan sirf SVG file banegi (dist folder mein):
          outputs: dist/github-snake.gif

      # Nayi file ko seedhe main branch mein commit karne ke liye
      - uses: EndBug/add-and-commit@v9
        with:
          branch: main
          default_author: github_actions
          message: 'ğŸ Snake animation updated'
          add: 'dist/github-snake.gif'
